name: Go
on:
  push:
    branches:
      - main
      - no_semaphore
  pull_request:
    branches:
      - main
      - no_semaphore

env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: mysecretpassword
  APP_DB_NAME: postgres
  APP_DB_PORT: 5432
jobs:
  build:
    name: "Build and Test"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
  sonarcloud:
    name: "SonarCloud Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

